------------------------------------------------------------------------------------------
--test connection to ORCLPDB1:
--sqlplus Debezium/dbz@localhost:1521/ORCLPDB1
-------------------------------------------
--SE tables
select * from Debezium.customers;
select * from Debezium.orders;
select * from Debezium.products;
select * from Debezium.products_on_hand;

-------------------------------------------
--activate AUTOCOMMIT
SET AUTOCOMMIT ON;
--insert some tows
INSERT INTO CUSTOMERS VALUES (NULL, 'Peter', 'Parker', 'peter.parker@marvel.com');
INSERT INTO CUSTOMERS VALUES (NULL, 'Peter1', 'Parker1', 'peter.parker@marvel.com1');
INSERT INTO CUSTOMERS VALUES (NULL, 'Peter2', 'Parker2', 'peter.parker@marvel.com2');
INSERT INTO CUSTOMERS VALUES (NULL, 'Peter3', 'Parker3', 'peter.parker@marvel.com3');
INSERT INTO CUSTOMERS VALUES (NULL, 'Peter4', 'Parker4', 'peter.parker@marvel.com4');
------------------------------------------------------------------------------------------
--update rows
UPDATE CUSTOMERS SET email = 'new_email@gmail.com' WHERE id = 1063;
DELETE FROM CUSTOMERS WHERE id = 1023;
------------------------------------------------------------------------------------------
SELECT name, open_mode FROM v$pdbs;
--SHOW CON_NAME;
ALTER SESSION SET CONTAINER=ORCLPDB1;
ALTER PLUGGABLE DATABASE RCLPDB1 OPEN;
--current db:
SHOW CON_NAME;
--SEE THE TABLE AND THE OWNER:
--sqlplus sys/top_secret@localhost:1521/ORCLPDB1 as sysdba
------------------------------------------------------------------------------------------
--DDL changes: after running th connector
CREATE TABLE product888 (
  id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 101) NOT NULL PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  description VARCHAR2(512),
  weight FLOAT
);
#
GRANT SELECT ON product888 to c##dbzuser;
ALTER TABLE product888 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
INSERT INTO product888 VALUES (NULL,'scooter1','Small scooter',7.84);
-----------------
--add new comumn will fail the connector---> compatibility topic name
-- prefix_topic1.DEBEZIUM.PRODUCT88 "NONE" and restart the connector.
ALTER TABLE product888 ADD new_column NUMBER DEFAULT 0 NOT NULL;
--insert some rows:
INSERT INTO product888 (name, description, weight) VALUES ('Laptop', 'High-performance laptop', 2.5);
INSERT INTO product888 (name, description, weight) VALUES ('Smartphone', 'Latest model with OLED display', 0.2);
INSERT INTO product888 (name, description, weight) VALUES ('Headphones', 'Noise-canceling over-ear headphones', 0.3);
--------------
--docker exec -it oracle bash -c 'sleep 1; sqlplus Debezium/dbz@localhost:1521/orclpdb1'
--docker exec -it oracle bash -c 'sleep 1; sqlplus sys/top_secret@//localhost:1521/ORCLPDB1'
--------------

